"use client";

import { useState, useCallback, useEffect } from "react";
import { Copy, Clock, Calendar, Zap, Check } from "lucide-react";
import Sidebar from "../components/SideBar";
import { motion, AnimatePresence } from "framer-motion";

// --- Data Constants ---
const CRON_PRESETS: Record<
    string,
    { value: string; description: string; example: string }
> = {
    "every-minute": {
        value: "* * * * *",
        description: "Runs every minute. Be cautious, this can overload systems.",
        example: "*/1 * * * * /usr/bin/php /var/www/artisan schedule:run",
    },
    "every-5-min": {
        value: "*/5 * * * *",
        description: "Runs every 5 minutes. Ideal for periodic checks.",
        example: "*/5 * * * * curl https://yourapi.com/ping",
    },
    hourly: {
        value: "0 * * * *",
        description: "Runs at the beginning of every hour (e.g., 01:00, 02:00).",
        example: "0 * * * * systemctl restart nginx",
    },
    daily: {
        value: "0 0 * * *",
        description: "Runs every day at midnight (00:00).",
        example: "0 0 * * * backup.sh",
    },
    weekly: {
        value: "0 0 * * 0",
        description: "Runs every Sunday at midnight (00:00). Sunday is day '0' or '7'.",
        example: "0 0 * * 0 certbot renew --quiet",
    },
    monthly: {
        value: "0 0 1 * *",
        description: "Runs on the 1st day of every month at midnight.",
        example: "0 0 1 * * logrotate /etc/logrotate.conf",
    },
    yearly: {
        value: "0 0 1 1 *",
        description: "Runs every January 1st at midnight.",
        example: "0 0 1 1 * echo 'Happy New Year!'",
    },
    "@reboot": {
        value: "@reboot",
        description: "Non-standard, runs once when the system starts up.",
        example: "@reboot docker start my_container",
    },
};

// --- Component ---

export default function CronGenerator() {
    const [interval, setInterval] = useState("daily"); // Set a default interval
    const [command, setCommand] = useState("/usr/bin/php /var/www/artisan schedule:run"); // Default command
    const [cron, setCron] = useState("");
    const [copied, setCopied] = useState(false);

    // Initial command generation and update on state change
    useEffect(() => {
        if (interval && command) {
            const preset = CRON_PRESETS[interval];
            const newCron = `${preset.value} ${command}`.trim();
            setCron(newCron);
        } else {
            setCron("");
        }
    }, [interval, command]);

    const copyToClipboard = useCallback(async () => {
        if (!cron) return;
        try {
            await navigator.clipboard.writeText(cron);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error("Failed to copy:", err);
        }
    }, [cron]);


    // Simplified generation for the button, though it's already generated by useEffect
    const generate = () => {
        // Force update cron output (useful if command changes without interval changing)
        const preset = CRON_PRESETS[interval];
        if (preset && command) {
             setCron(`${preset.value} ${command}`.trim());
        }
    };

    return (
        // Dark Mode Base Styling
        <div className="flex min-h-screen bg-gradient-to-br from-gray-900 to-gray-950 text-gray-100">

            {/* Note: In a real Next.js/React app, Sidebar placement should be consistent.
                I'm keeping the original fixed structure for this demonstration. */}
            <div className="fixed left-0 top-0 h-full">
                <Sidebar />
            </div>

            {/* MAIN CONTENT */}
            {/* Adjusted margin for Sidebar */}
            <main className="ml-[260px] w-full p-6 md:p-10 max-w-4xl">

                {/* Header */}
                <div className="flex items-center gap-4 mb-10">
                    <div className="p-3 bg-gradient-to-br from-purple-600 to-indigo-700 rounded-xl shadow-lg">
                        <Clock className="w-6 h-6 text-white" />
                    </div>
                    <h1 className="text-3xl font-bold bg-gradient-to-r from-white to-purple-400 bg-clip-text text-transparent">
                        Cronjob Schedule Generator
                    </h1>
                </div>

                <div className="grid md:grid-cols-2 gap-8">
                    {/* LEFT COLUMN: INTERVAL SELECTION */}
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="bg-gray-800 rounded-2xl border border-gray-700 p-6 shadow-xl h-full"
                    >
                        <h2 className="text-xl font-semibold text-gray-200 mb-4 flex items-center gap-2">
                            <Calendar className="w-5 h-5 text-indigo-400" /> 
                            1. Select Run Interval
                        </h2>

                        <label className="block mb-2 font-medium text-gray-400">Execution Frequency</label>
                        <select
                            className="w-full p-3 rounded-xl border border-gray-700 bg-gray-900 text-white focus:ring-2 focus:ring-indigo-500 transition-shadow appearance-none"
                            value={interval}
                            onChange={(e) => setInterval(e.target.value)}
                        >
                            {Object.entries(CRON_PRESETS).map(([key, preset]) => (
                                <option key={key} value={key}>
                                    {preset.description.split('.')[0]} ({preset.value})
                                </option>
                            ))}
                        </select>
                        
                        {/* DESCRIPTION + EXAMPLE */}
                        {interval && CRON_PRESETS[interval] && (
                            <motion.div
                                key={interval}
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                className="mt-6 bg-gray-900 border border-gray-700 p-4 rounded-xl"
                            >
                                <p className="text-sm text-indigo-400 mb-2 font-semibold">
                                    Pattern: <code className="text-sm font-mono text-white">{CRON_PRESETS[interval].value}</code>
                                </p>
                                <p className="text-sm text-gray-400">
                                    {CRON_PRESETS[interval].description}
                                </p>
                                <p className="text-xs text-gray-500 mt-3 border-t border-gray-700 pt-3">
                                    <span className="font-semibold text-gray-300">
                                        Example:
                                    </span>
                                    <br />
                                    <code className="text-xs text-gray-400 break-all">{CRON_PRESETS[interval].example}</code>
                                </p>
                            </motion.div>
                        )}
                    </motion.div>

                    {/* RIGHT COLUMN: COMMAND INPUT */}
                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="bg-gray-800 rounded-2xl border border-gray-700 p-6 shadow-xl h-full flex flex-col justify-between"
                    >
                        <div>
                            <h2 className="text-xl font-semibold text-gray-200 mb-4 flex items-center gap-2">
                                <Zap className="w-5 h-5 text-amber-400" />
                                2. Define Command
                            </h2>

                            <label className="block mb-2 font-medium text-gray-400">
                                Full command path to execute
                            </label>
                            <input
                                type="text"
                                placeholder="e.g., /path/to/script.sh"
                                className="w-full p-3 rounded-xl border border-gray-700 bg-gray-900 text-white placeholder-gray-500 focus:ring-2 focus:ring-amber-500 transition-shadow"
                                value={command}
                                onChange={(e) => setCommand(e.target.value)}
                            />

                            <button
                                onClick={generate}
                                className="w-full py-3 mt-6 bg-gradient-to-r from-indigo-500 to-purple-600 text-white rounded-xl font-semibold hover:from-indigo-600 hover:to-purple-700 transition-all shadow-lg shadow-purple-500/30"
                            >
                                Generate Full Cronjob String
                            </button>
                        </div>

                        {/* CRON STRUCTURE EXPLANATION */}
                        <div className="mt-6 pt-6 border-t border-gray-700">
                            <h3 className="text-sm font-semibold text-gray-400 mb-2">Cron Syntax Breakdown</h3>
                            <div className="bg-gray-900 p-3 rounded-lg font-mono text-xs text-gray-300 overflow-x-auto">
                                <span className="text-red-400">m</span> <span className="text-orange-400">h</span> <span className="text-yellow-400">dom</span> <span className="text-green-400">mon</span> <span className="text-blue-400">dow</span> <span className="text-gray-400">command</span>
                                <p className="text-xs text-gray-500 mt-1">
                                    (Minute Hour Day-of-Month Month Day-of-Week)
                                </p>
                            </div>
                            {/* Diagram Trigger */}
                            
                        </div>
                    </motion.div>
                </div>

                {/* OUTPUT SECTION */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mt-8 p-6 bg-gradient-to-br from-black to-gray-900 rounded-2xl border border-indigo-700 shadow-2xl"
                >
                    <h2 className="text-xl font-semibold text-gray-200 mb-4">3. Final Cron Command</h2>

                    {/* Output Box */}
                    <div className="relative group">
                        <div className="bg-gray-900 rounded-xl p-4 border border-indigo-500 shadow-lg shadow-indigo-900/50">
                            <code className="text-gray-100 font-mono text-sm md:text-base block pr-16 overflow-x-auto">
                                <span className="text-gray-500 select-none">$ </span>
                                {cron || "Select an interval and enter a command above."}
                            </code>
                        </div>

                        {/* Copy Button */}
                        {cron && (
                            <motion.button
                                onClick={copyToClipboard}
                                className={`absolute top-1/2 -translate-y-1/2 right-3 p-3 rounded-full transition-all flex items-center justify-center ${copied 
                                    ? "bg-emerald-600 text-white" 
                                    : "bg-indigo-600 text-white hover:bg-indigo-500"
                                }`}
                                whileHover={{ scale: 1.05 }}
                                whileTap={{ scale: 0.95 }}
                                title="Copy to clipboard"
                            >
                                <AnimatePresence mode="wait">
                                    {copied ? (
                                        <motion.div
                                            key="check"
                                            initial={{ opacity: 0, scale: 0.5 }}
                                            animate={{ opacity: 1, scale: 1 }}
                                            exit={{ opacity: 0, scale: 0.5 }}
                                        >
                                            <Check size={20} />
                                        </motion.div>
                                    ) : (
                                        <motion.div
                                            key="copy"
                                            initial={{ opacity: 0, scale: 0.5 }}
                                            animate={{ opacity: 1, scale: 1 }}
                                            exit={{ opacity: 0, scale: 0.5 }}
                                        >
                                            <Copy size={20} />
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.button>
                        )}
                    </div>
                </motion.div>
            </main>
        </div>
    );
}